---
- hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        
    - name: Install basic packages
      apt:
        name:
          - ca-certificates
          - curl
          - python3
          - python3-pip
        state: present
        update_cache: True

    - name: "Install Python modules"
      pip:
        name: 
          - ansible
          - netaddr
        state: present

    - name: Creating allowing to read the syslog file
      ansible.builtin.shell:
        cmd: sudo chmod o+r /var/log/syslog

    - name: Creating a link
      ansible.builtin.shell:
        cmd: sudo ln -s /var/log/syslog /var/log/linktosyslog.log

- name: Webservers
  hosts: webservers
  become: true
  tasks:
    - name: install nginx
      apt: 
        name: nginx 
        state: present

    - name: Creating allowing to read the syslog file
      ansible.builtin.shell:
        cmd: sudo sudo chmod o+r /var/log/nginx/access.log

    - name: Creating a link
      ansible.builtin.shell:
        cmd: sudo ln -s /var/log/nginx/access.log /var/log/linktoaccesslog.log

    - name: Creating allowing to read the syslog file
      ansible.builtin.shell:
        cmd: sudo sudo chmod o+r /var/log/nginx/access.log

    - name: Creating a link
      ansible.builtin.shell:
        cmd: sudo ln -s /var/log/nginx/error.log /var/log/linktoerrorlog.log

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy "index.html" to default Nginx location
      copy:
        src: ./templates/index.html
        dest: /var/www/html/index.nginx-debian.html
        mode: 0644
      notify:
         - Restart Nginx
  
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted


- name: zabbix-server
  hosts: zabbix-server
  become: true
  vars:
    pg_hba_conf: /etc/postgresql/14/main/pg_hba.conf
    postgresql_conf: /etc/postgresql/14/main/postgresql.conf
  tasks:
    - name: Ensure required packages are installed
      apt:
        name: 
          - wget
          - gnupg
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python3-pip
          - python3-dev
          - python3-venv
          - python3-psycopg2
        state: present

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Download Zabbix release package
      get_url:
        url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
        dest: /home/ubuntu/zabbix-release.deb


    - name: Install Zabbix release package using dpkg
      apt:
        deb: /home/ubuntu/zabbix-release.deb

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix server and related packages
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - php8.1-pgsql
        state: present

    - name: Ensure PostgreSQL is installed
      apt:
        name: postgresql
        state: present

    - name: Ensure the PostgreSQL client is installed
      apt:
        name: postgresql-client
        state: present

    - name: Install PostgreSQL development libraries (optional)
      apt:
        name: libpq-dev
        state: present

    - name: Ensure PostgreSQL is running and enabled
      service:
        name: postgresql
        state: started
        enabled: true

- name: "PostgreSQL Database prep"
  hosts: zabbix-server
  become: true
  become_user: postgres
  tasks:
    - name: "PostgreSQL | Create database"
      community.postgresql.postgresql_db:
        login_user: "postgres"
        login_password: "postgres"
        login_host: "localhost"
        port: 5432
        login_unix_socket: ""
        name: "zabbix"

    - name: "PostgreSQL | Create database user"
      community.postgresql.postgresql_user:
        login_user: "postgres"
        login_password: "postgres"
        login_host: "localhost"
        port: 5432
        login_unix_socket: ""
        name: "zabbix"
        password: "md5{{ ('zabbix' + 'zabbix') | hash('md5') }}"

    - name: "PostgreSQL | Set database/user permissions"
      community.postgresql.postgresql_privs:
        login_user: "postgres"
        login_password: "postgres"
        login_host: "localhost"
        port: 5432
        login_unix_socket: ""
        db: "zabbix"
        privs: ALL
        type: schema
        objs: public
        role: "zabbix"

    - name: "PostgreSQL | Create timescaledb extension"
      community.postgresql.postgresql_ext:
        login_user: "postgres"
        login_password: "postgres"
        login_host: "localhost"
        port: 5432
        login_unix_socket: ""
        db: "zabbix"
        name: timescaledb

    - name: "PostgreSQL | Get current database version"
      community.postgresql.postgresql_query:
        login_user: "zabbix"
        login_password: "zabbix"
        login_host: "localhost"
        port: 5432
        db: "zabbix"
        query: "SELECT mandatory FROM dbversion"

    - name: "PostgreSQL | Import schema"
      community.postgresql.postgresql_db:
        login_user: "zabbix"
        login_password: "zabbix"
        login_host: "localhost"
        port: 5432
        db: "zabbix"
        state: restore
        target: "/usr/share/doc/zabbix-sql-schema/postgresql/server.sql.gz"


    - name: "PostgreSQL | Check if TimescaleDB has been configured"
      community.postgresql.postgresql_query:
        login_user: "zabbix"
        login_password: "zabbix"
        login_host: "localhost"
        port: 5432
        db: "zabbix"
        query: "SELECT db_extension FROM config WHERE db_extension = 'timescaledb'"
      register: _config_db_extension

- name: Install Zabbix Agent
  hosts: zabbix-agents
  become: true
  tasks:
      
    - name: Ensure wget is installed
      apt:
        name: wget
        state: present

    - name: Download Zabbix release package
      get_url:
        url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
        dest: /home/ubuntu/zabbix-release.deb

    - name: Install Zabbix release package using dpkg
      apt:
        deb: /home/ubuntu/zabbix-release.deb

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present

    - name: Update Zabbix agent configuration
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=fhmhm1omke642ji3q09n.auto.internal' #IP-HERE
        state: present

    - name: Update Zabbix agent configuration
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^AllowRoot='
        line: 'AllowRoot=1' 
        state: present

    - name: Update Zabbix agent configuration
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive=127.0.0.1'
        line: 'ServerActive=fhmhm1omke642ji3q09n.auto.internal' 
        state: present

    - name: Restart Zabbix agent service
      service:
        name: zabbix-agent
        state: restarted

    - name: Enable Zabbix agent service at boot
      service:
        name: zabbix-agent
        enabled: true

- name: Install and configure Elasticsearch
  hosts: Elasticsearch
  become: true
  tasks:
    - name: Update package list and install dependencies
      apt:
        update_cache: yes
        name: 
          - gnupg
          - apt-transport-https
        state: present

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main"
        state: present
        filename: 'elastic-7.x'
    
    - name: Add Elasticsearch repository
      apt_repository:
        repo: 'deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main'
        state: present


    - name: Update package list and install Elasticsearch
      apt:
        update_cache: yes
        name: elasticsearch
        state: present

    - name: Reload systemd configuration
      ansible.builtin.shell:
        cmd: sudo systemctl daemon-reload

    - name: Enable elasticsearch.service
      systemd:
        name: elasticsearch
        enabled: yes

    - name: Deploy elasticsearch.yml from template
      copy:
        src: ./templates/Elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: elasticsearch
        group: elasticsearch
        mode: '0644'

    - name: Restart Elasticsearch
      systemd:
        name: elasticsearch
        state: restarted

- name: Install and configure Kibana
  hosts: Kibana
  become: yes
  tasks:

    - name: Update package list
      apt:
        update_cache: yes

    - name: Install wget and apt-transport-https
      apt:
        name:
          - wget
          - apt-transport-https
        state: present
   
    - name: Add Elasticsearch repository
      apt_repository:
        repo: 'deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main'
        state: present

    - name: Update apt package list after adding Elasticsearch repository
      apt:
        update_cache: yes

    - name: Install Kibana
      apt:
        name: kibana
        state: present

    - name: Reload systemd configuration
      ansible.builtin.shell:
        cmd: sudo systemctl daemon-reload

    - name: Enable kibana.service
      systemd:
        name: kibana
        enabled: yes

    - name: Start kibana.service
      systemd:
        name: kibana
        state: started

    - name: Configure /etc/kibana/kibana.yml
      copy:
        src: ./templates/kibana.yml
        dest: /etc/kibana/kibana.yml

    - name: Restart Kibana
      systemd:
        name: kibana
        state: restarted

- name: Install and configure Filebeat
  hosts: Filebeat
  become: yes
  tasks:

    - name: Update package list
      apt:
        update_cache: yes

    - name: Install wget and apt-transport-https
      apt:
        name:
          - wget
          - apt-transport-https
        state: present
   
    - name: Add Elasticsearch repository
      apt_repository:
        repo: 'deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main'
        state: present

    - name: Update apt package list after adding Elasticsearch repository
      apt:
        update_cache: yes

    - name: Install Filebeat
      apt:
        name: filebeat
        state: present

    - name: Reload systemd configuration
      ansible.builtin.shell:
        cmd: sudo systemctl daemon-reload

    - name: Enable filebeat.service
      systemd:
        name: filebeat
        enabled: yes

    - name: Start filebeat.service
      systemd:
        name: filebeat
        state: started

    - name: Configure Filebeat
      copy:
        src: ./templates/filebeat.yml
        dest: /etc/filebeat/filebeat.yml
      notify:
        - Restart Filebeat

  handlers:
    - name: Restart Filebeat
      systemd:
        name: filebeat
        state: restarted
