---
- hosts: bastion
  become: true
  tasks:
    - name: Copy SSH private key
      copy:
        src: /home/limzor/.ssh/bastionkey
        dest: /home/ubuntu/.ssh/bastionkey
        mode: '0600'

    - name: Copy SSH public key
      copy:
        src: /home/limzor/.ssh/bastionkey.pub
        dest: /home/ubuntu/.ssh/bastionkey.pub
        mode: '0644'

    - name: Copy Ansible configuration files
      copy:
        src: /home/limzor/AnsibleSetup/GrandProject...
        dest: /home/ubuntu/
        mode: '0644'

    - name: Creating allowing to read the syslog file
      ansible.builtin.shell:
        cmd: sudo chmod o+r /var/log/syslog

    - name: Creating a link
      ansible.builtin.shell:
        cmd: sudo ln -s /var/log/syslog /var/log/linktosyslog.log

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install basic packages
      apt:
        name:
          - ca-certificates
          - curl
          - python3
          - python3-pip
          - git
          - ansible
        state: present
        update_cache: true

    - name: Install Python modules
      pip:
        name: 
          - ansible
          - netaddr
        state: present

    - name: Installing community.general
      community.general.ansible_galaxy_install:
        type: collection
        name: community.general

    - name: Ensure wget is installed
      apt:
        name: wget
        state: present

    - name: Download Zabbix release package
      get_url:
        url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release.deb

    - name: Install Zabbix release package using dpkg
      apt:
        deb: /tmp/zabbix-release.deb

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present

    - name: Update Zabbix agent configuration
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=127.0.0.1,89.169.136.69,10.0.0.17'  # Update with the actual IP address of the Zabbix server
        state: present

    - name: Restart Zabbix agent service
      service:
        name: zabbix-agent
        state: restarted

    - name: Enable Zabbix agent service at boot
      service:
        name: zabbix-agent
        enabled: true
